[project]
name = "mytradingview"
version = "0.1.0"
description = "My TradingView"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "robyn>=0.69.0",
    "orjson>=3.9.15",
    "ccxt>=4.4.89",
    "aiosqlite>=0.21.0",
    "nuitka>=2.7.7",
    "aiohttp>=3.12.13"
]